export const massachusettsCities = [
  'boston',
  'worcester', 
  'springfield',
  'lowell',
  'cambridge',
  'newton',
  'framingham',
  'quincy',
  'brockton',
  'lynn',
  'somerville',
  'lawrence',
  'new-bedford',
  'fall-river',
  'malden',
  'medford',
  'peabody',
  'revere',
  'waltham',
  'taunton'
];

export const cityDisplayNames: Record<string, string> = {
  'boston': 'Boston',
  'worcester': 'Worcester',
  'springfield': 'Springfield', 
  'lowell': 'Lowell',
  'cambridge': 'Cambridge',
  'newton': 'Newton',
  'framingham': 'Framingham',
  'quincy': 'Quincy',
  'brockton': 'Brockton',
  'lynn': 'Lynn',
  'somerville': 'Somerville',
  'lawrence': 'Lawrence',
  'new-bedford': 'New Bedford',
  'fall-river': 'Fall River',
  'malden': 'Malden',
  'medford': 'Medford',
  'peabody': 'Peabody',
  'revere': 'Revere',
  'waltham': 'Waltham',
  'taunton': 'Taunton'
};

export const cityDescriptions: Record<string, string> = {
  'boston': 'Solar panel installation and consultation services in Boston, Massachusetts. Save money on energy bills with professional solar solutions in the Greater Boston area.',
  'worcester': 'Professional solar energy services in Worcester, MA. Get free solar consultation and start your journey to energy independence in Central Massachusetts.',
  'springfield': 'Solar panel experts serving Springfield and Western Massachusetts. Discover how solar energy can reduce your electricity costs.',
  'lowell': 'Solar installation services in Lowell, Massachusetts. Join your neighbors in saving money with clean, renewable solar energy.',
  'cambridge': 'Cambridge solar panel installation by Solar Señorita. Expert consultation and installation services for Cambridge residents.',
  'newton': 'Solar energy solutions for Newton, Massachusetts homeowners. Free consultation and professional installation services.',
  'framingham': 'Framingham solar panel installation and consultation. Start saving on energy bills with professional solar services.',
  'quincy': 'Solar panel services in Quincy, MA. Professional installation and free consultation for South Shore residents.',
  'brockton': 'Brockton solar energy expert services. Get your free consultation and learn about solar savings in your area.',
  'lynn': 'Lynn, Massachusetts solar panel installation. Professional solar services for North Shore residents.',
  'somerville': 'Somerville solar energy consultation and installation. Expert solar services for Greater Boston residents.',
  'lawrence': 'Lawrence, MA solar panel experts. Free consultation and professional installation services.',
  'new-bedford': 'New Bedford solar energy services. Professional solar panel installation for South Coast Massachusetts.',
  'fall-river': 'Fall River solar panel installation and consultation services. Start saving with solar energy.',
  'malden': 'Malden, Massachusetts solar energy experts. Free consultation and professional solar panel installation.',
  'medford': 'Medford solar panel services. Professional installation and consultation for Greater Boston area.',
  'peabody': 'Peabody solar energy solutions. Expert consultation and installation services for North Shore residents.',
  'revere': 'Revere, MA solar panel installation. Professional solar services for coastal Massachusetts residents.',
  'waltham': 'Waltham solar energy consultation and installation. Expert services for MetroWest Massachusetts.',
  'taunton': 'Taunton solar panel experts. Professional installation and free consultation services for southeastern Massachusetts.'
};